namespace SHOP_CENTER
{
    partial class Stock_report
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            this.button1 = new System.Windows.Forms.Button();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.button1);
            this.panel1.Controls.Add(this.comboBox1);
            this.panel1.Location = new System.Drawing.Point(40, 26);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(728, 89);
            this.panel1.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(345, 37);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(82, 24);
            this.button1.TabIndex = 1;
            this.button1.Text = "Search";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "",
            "A. Pakura",
            "A. Piyazo",
            "Dal",
            "Dal/baji",
            "Egg",
            "F. Egg Chop",
            "F. France Fry",
            "F. Parata",
            "F. Swiss Ban",
            "F.f  Club Sandwich",
            "F.f  Vegetable Roll",
            "F.f Chicken Kabab",
            "F.f Chicken Roll",
            "",
            "ticulars",
            "Beef Burger",
            "Chicken Roll",
            "Chicken Samucha",
            "Vegetable Singara",
            "Egg Chop",
            "Vegetable Samucha",
            "Chicken Cutlet",
            "L. Thahari (staff)",
            "Vegetable Singara",
            "Dr. 7up 250ml Botol",
            "L. Chicken Polau",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "Club Sandwich",
            "Firni",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Club Sandwich",
            "Chicken Cutlet",
            "L. Thahari (staff)",
            "Dr. Mirinda 500ml",
            "Dr. Mirinda 500ml",
            "Dr. Mirinda 500ml",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Club Sandwich",
            "Dr. Cocacola 400ml",
            "Dr. Cocacola 400ml",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Singara",
            "Chicken Friued Burgar",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Beef Burger",
            "Chicken Cutlet",
            "Chicken Friued Burgar",
            "Chicken Noodles",
            "Chicken Patties",
            "Chicken Pizza",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Samucha",
            "Chicken Sandwich",
            "Club Sandwich",
            "Dr. 7up 250ml",
            "L. Chicken Polau",
            "L. Chicken Polau",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Cutlet",
            "Chicken Pizza",
            "Chicken Sandwich",
            "Chicken Pizza",
            "Chicken Pizza",
            "Chicken Noodles",
            "Chicken Cutlet",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Samucha",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Samucha",
            "Club Sandwich",
            "Chicken Samucha",
            "Coffee",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Samucha",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "Egg Puding",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Beef Burger",
            "Chicken Cutlet",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandwich",
            "Club Sandwich",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Chicken Samucha",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken+ Rice",
            "L. Chicken Polau(staff)",
            "L. Chicken Polau(staff)",
            "Vegetable Roll",
            "Dr. Mountain Dew 250ml",
            "Dr. Mountain Dew 250ml",
            "Dr. Mountain Dew 500ml",
            "Dr. Mirinda 500ml",
            "Dr. Mountain Dew 500ml",
            "Dr. Mountain Dew 500ml",
            "Dr. Pepsi 500ml",
            "Dr. Pepsi 250ml",
            "Dr. Mirinda 500ml",
            "Club Sandwich",
            "Dr. Mirinda 250ml",
            "Dr. 7up 500ml",
            "Dr. 7up 500ml",
            "Dr. Pepsi 250ml",
            "Dr. Mirinda 250ml",
            "Dr. Pepsi 500ml",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Vegetable Roll",
            "Chicken Sandwich",
            "Chicken Cutlet",
            "Coffee",
            "Dr. 7up 250ml",
            "Dr. Water (0.5) Letter",
            "Egg Puding",
            "Egg Chop",
            "Egg",
            "Vegetable",
            "Tea",
            "Ruti",
            "Vegetable Singara",
            "Chicken Samucha",
            "Vegetable Samucha",
            "Egg Puding",
            "Pacura",
            "Pacura",
            "Egg Chop",
            "Chicken Cutlet",
            "L. Thahari (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Thahari (staff)",
            "L. Thahari",
            "L. Fish/egg+veg+rice+dal",
            "Chicken Pizza",
            "Chicken Sandwich",
            "Coffee",
            "Dr. 7up 250ml",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Roll",
            "Tea",
            "Chicken Samucha",
            "Chicken Roll",
            "Pacura",
            "Kima Parata",
            "Kima Parata",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Chicken Samucha",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Beef Burger",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Club Sandwich",
            "Club Sandwich",
            "Chicken Sandwich",
            "Chicken Roll",
            "Chicken Pizza",
            "Vegetable Roll",
            "Chicken Cutlet",
            "Egg Puding",
            "Egg Puding",
            "Egg",
            "L. Veg+dal+rice (staff)",
            "Coffee",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Vegetable Singara",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Tea",
            "Coffee",
            "Chicken Sandwich",
            "Chicken Cutlet",
            "Chicken Samucha",
            "Rice",
            "Chicken Cutlet",
            "Chicken Pizza",
            "Chicken Friued Burgar",
            "Club Sandwich",
            "Egg Puding",
            "Dr. Water 1.5 Ltr",
            "Chicken Sandwich",
            "Chicken Samucha",
            "Club Sandwich",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Vegetable Roll",
            "Vegetable Samucha",
            "Chicken Pizza",
            "Coffee",
            "I. Chocbar",
            "I. Corneli",
            "I. Chocbar",
            "I. Malay",
            "I. Malay",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Dr. Water 1.5 Ltr",
            "Dr. Water (0.5) Letter",
            "Chicken Samucha",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Chicken Sandwich",
            "Club Sandwich",
            "Club Sandwich",
            "Beef Burger",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Vegetable Roll",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Chicken Samucha",
            "L. Chicken Polau(staff)",
            "L. Chicken Polau",
            "Coffee",
            "Coffee",
            "Dr. Mirinda 500ml",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "Egg Puding",
            "Vegetable Singara",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Chicken Samucha",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Dr. Mountain Dew 250ml",
            "Vegetable Singara",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Singara",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Chicken Samucha",
            "Kima Parata",
            "Club Sandwich",
            "Beef Burger",
            "Chicken Sandwich",
            "Vegetable Roll",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Friued Burgar",
            "Egg Chop",
            "Chicken Cutlet",
            "Pacura",
            "Chicken Roll",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Chicken Sandwich",
            "Kima Parata",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Egg Chop",
            "Chicken Cutlet",
            "Pacura",
            "Pacura",
            "L. Thahari",
            "L. Thahari",
            "L. Thahari (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Egg Puding",
            "Egg Puding",
            "Coffee",
            "Chicken Cutlet",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Samucha",
            "Chicken Sandwich",
            "Pacura",
            "Vegetable Roll",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Tea",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Sandwich",
            "Club Sandwich",
            "Chicken Sandwich",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Vegetable Roll",
            "Beef Burger",
            "Kima Parata",
            "Egg Chop",
            "Chicken Samucha",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "I. Mega",
            "I. Corneli- White",
            "I. Corneli- White",
            "I. Macho",
            "I. Loly",
            "I. Vanilla",
            "I. Shell And- Core",
            "I. Chocbar",
            "I. Chocolate Ice- Cream",
            "I. Chocolate Ice- Cream",
            "I. Malay",
            "I. Chocolateorange",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Kima Parata",
            "Chicken Pizza",
            "Chicken Roll",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "Egg Puding",
            "Pacura",
            "Chicken Cutlet",
            "Egg Chop",
            "L. Fish/egg+veg+rice+dal (staff)",
            "I. Mega",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Kima Parata",
            "Kima Parata",
            "Kima Parata",
            "Chicken Sandwich",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Roll",
            "Chicken Samucha",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Chicken Roll",
            "Chicken Pizza",
            "Egg",
            "Vegetable Singara",
            "Pacura",
            "Chicken Samucha",
            "Vegetable Samucha",
            "Egg Chop",
            "Egg Puding",
            "Chicken Cutlet",
            "L. Chicken Polau(staff)",
            "L. Chicken Polau",
            "L. Chicken Polau",
            "L. Chicken Polau",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Dr. Sprite (600ml)",
            "Dr. 7up 500ml",
            "Dr. 7up 250ml",
            "Dr. Mirinda 500ml",
            "Dr. Mirinda 250ml",
            "Dr. Pepsi 500ml Diet",
            "Dr. Pepsi 250ml",
            "Coffee",
            "Dr. Mirinda 250ml",
            "Chicken Sandwich",
            "Chicken Samucha",
            "Club Sandwich",
            "Chicken Roll",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Pizza",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Samucha",
            "Vegetable Samucha",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Singara",
            "Pacura",
            "Egg Chop",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Kima Parata",
            "Chicken Pizza",
            "Chicken Roll",
            "Vegetable Singara",
            "Chicken Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "Egg Puding",
            "Chicken Cutlet",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Chicken Sandwich",
            "Club Sandwich",
            "Chicken Pizza",
            "Beef Burger",
            "Chicken Roll",
            "Chicken Friued Burgar",
            "Vegetable Roll",
            "Kima Parata",
            "Kima Parata",
            "Vegetable Singara",
            "Rice",
            "Chicken Friued Burgar",
            "Chicken Samucha",
            "Vegetable Singara",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Chicken Sandwich",
            "Egg Puding",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Chicken Samucha",
            "Vegetable Singara",
            "Pacura",
            "Soup",
            "L. Chicken Polau",
            "L. Khasi+rice+dal+(staff)",
            "L. Veg+dal+rice (staff)",
            "Kima Parata",
            "Chicken Pizza",
            "Beef Burger",
            "Chicken Sandwich",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Pacura",
            "Chicken Cutlet",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "I. Mega",
            "I. Mega",
            "I. Macho",
            "I. Chocbar",
            "I. Chocolateorange",
            "I. Chocolateorange",
            "I. Corneli- White",
            "I. Corneli- White",
            "I. Corneli",
            "I. Corneli",
            "I. Corneli",
            "I. Vanilla",
            "I. Shell And- Core",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Chicken Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "Egg Puding",
            "Dr. 7up 250ml",
            "Dr. 7up 500ml",
            "Dr. 7up 250ml",
            "Dr. 7up 500ml",
            "Dr. Fanta Can(600ml)",
            "Dr. Fanta Can(600ml)",
            "Dr. Pepsi 500ml",
            "Dr. Sprite (600ml)",
            "Dr. Sprite (600ml)",
            "Dr. Mirinda 250ml",
            "Dr. Pepsi 500ml",
            "Coffee",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandwich",
            "Club Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Kima Parata",
            "Chicken Pizza",
            "Beef Burger",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken Polau(staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Pizza",
            "Chicken Sandwich",
            "Chicken Sandwich",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Roll",
            "Tea",
            "L. Chicken Polau(staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Dr. Water 1.5 Ltr",
            "Dr. Water 1.5 Ltr",
            "Vegetable Roll",
            "Chicken Roll",
            "Chicken Roll",
            "L. Veg+dal+rice (staff)",
            "Soup",
            "Ruti",
            "Tea",
            "Rice",
            "Sauce Hot Tomato",
            "Chicken Sandwich",
            "I. Corneli",
            "L. Vegetable + Fry",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice",
            "L. Veg+dal+rice",
            "L. Vaji",
            "L. Vaji",
            "Club Sandwich",
            "Chicken Samucha",
            "Chicken Roll",
            "Egg Puding",
            "Chicken Pizza",
            "Egg Puding",
            "I. Chocbar",
            "Egg Puding",
            "I. Mega",
            "I. Loly",
            "I. Corneli",
            "I. Corneli- White",
            "I. Macho",
            "I. Shell And- Core",
            "I. Vanilla",
            "I. Chocolate Ice- Cream",
            "Chicken Samucha",
            "Vegetable Singara",
            "Vegetable Samucha",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "Egg Puding",
            "Vegetable Singara",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Roll",
            "Kima Parata",
            "Egg Puding",
            "Chicken Samucha",
            "Vegetable Samucha",
            "Vegetable Singara",
            "Vegetable Singara",
            "L. Veg+dal+rice (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Chicken Pizza",
            "Vegetable Singara",
            "Vegetable Samucha",
            "Chicken Samucha",
            "Tea",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Vegetable Samucha",
            "Egg Puding",
            "L. Thahari (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Thahari (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Thahari",
            "L. Vaji",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice",
            "L. Veg+dal+rice (staff)",
            "L. Dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Alachi Biscuit",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Dr. Water (0.5) Letter",
            "Dr. Water 1.5 Ltr",
            "Dr. Water (0.5) Letter",
            "I. Blackforest Belgium",
            "Tea",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken",
            "L. Chicken Polau",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Meat",
            "L. Khasi",
            "L. Thahari",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Veg+dal+rice (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Chicken Sandwich",
            "Chicken Pizza",
            "Kima Parata",
            "Chicken Roll",
            "Club Sandwich",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Coffee",
            "Coffee",
            "Tea",
            "Tea",
            "Orange+ Malta",
            "I. Chocbar",
            "Coffee",
            "Tea",
            "Coffee",
            "Vegetable",
            "Vegetable Roll",
            "Tea",
            "Kima Parata",
            "Chicken Pizza",
            "Chicken Sandwich",
            "Chicken Roll",
            "Club Sandwich",
            "Chicken Friued Burgar",
            "Vegetable Roll",
            "Beef Burger",
            "L. Khasi+rice+dal+(staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Thahari (staff)",
            "Egg Puding",
            "Coffee",
            "I. Shell And- Core",
            "I. Corneli-classic",
            "I. Mega",
            "Egg Puding",
            "I. Chocolateorange",
            "Vegetable Roll",
            "Chicken Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Egg Puding",
            "L. Chicken Polau(staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Egg+rice+dal+veg",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Khasi+rice+dal+(staff)",
            "L. Khasi+rice+dal",
            "Chicken Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Sandwich",
            "Chicken Sandwich",
            "Club Sandwich",
            "Egg Puding",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "Kima Parata",
            "Vegetable Roll",
            "L. Chicken Polau(staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal",
            "Beef Burger",
            "Chicken Pizza",
            "I. Vanilla",
            "I. Malay",
            "Egg Puding",
            "Chicken Friued Burgar",
            "Chicken Samucha",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Chicken Pizza",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Chicken Sandews",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Roll",
            "L. Veg+dal+rice (staff)",
            "L. Vegetable + Fry",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "Chicken Roll",
            "Beef Burger",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Roll",
            "Egg Puding",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Kima Parata",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Veg+dal+rice (staff)",
            "Egg Puding",
            "Vegetable Samucha",
            "Ruti",
            "Telapia",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "L. Beef/ Rice+ Dal+vegetable",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Club Sandwich",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Chicken Pizza",
            "Kima Parata",
            "Chicken Friued Burgar",
            "Beef Burger",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Egg+rice+dal+veg",
            "Egg Puding",
            "Chicken Friued Burgar",
            "Beef Burger",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Kima Parata",
            "L. Khichuri+elish+borta",
            "I. Vanilla",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Beef/ Rice+ Dal+vegetable",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "Egg Puding",
            "Tea",
            "Alachi Biscuit",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Fish/egg+veg+rice+dal",
            "Chicken Pizza",
            "Sauce Hot Tomato",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Egg+rice+dal+veg",
            "L. Chicken+ Rice",
            "L. Dal",
            "L. Khasi+rice+dal+(staff)",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Roll",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Chicken Pizza",
            "Beef Burger",
            "Beef Burger",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Lexus Biscuit",
            "I. Blackforest Belgium",
            "I. Chocbar",
            "I. Chocolate Ice- Cream",
            "I. Corneli Belgium Choclate",
            "I. Corneli-classic",
            "I. Loly",
            "I. Macho",
            "I. Malay",
            "I. Mega",
            "I. Vanilla",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice",
            "L. Khichuri+elish+borta",
            "Vegetable Singara",
            "Egg Puding",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "Egg Puding",
            "Chicken Sandews",
            "Club Sandwich",
            "Chicken Friued Burgar",
            "Beef Burger",
            "Chicken Pizza",
            "Kima Parata",
            "Chicken Roll",
            "Vegetable Roll",
            "Vegetable Singara",
            "Vegetable Singara",
            "Chicken Samucha",
            "Egg Puding",
            "Vegetable Singara",
            "I. Vanilla",
            "I. Loly",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Beef Burger",
            "Vegetable Roll",
            "Kima Parata",
            "Coffee",
            "Coffee",
            "Lexus Biscuit",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Egg+rice+dal+veg",
            "D. Fanta Can(250ml)",
            "L. Egg+rice+dal+veg",
            "I. Blackforest Belgium",
            "I. Loly",
            "I. Chocbar",
            "I. Corneli Belgium Choclate",
            "I. Corneli-classic",
            "I. Macho",
            "I. Malay",
            "I. Mega",
            "I. Shell And- Core",
            "I. Vanilla",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "L. Veg+dal+rice (staff)",
            "Vegetable Roll",
            "Chicken Samucha",
            "Vegetable Singara",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Egg Puding",
            "Chicken Samucha",
            "Vegetable Singara",
            "Egg Puding",
            "Vegetable Singara",
            "Vegetable Singara",
            "Chicken Samucha",
            "Chicken Samucha",
            "Egg Puding",
            "L. Khasi+rice+dal+(staff)",
            "L. Egg+rice+dal+veg",
            "L. Fish/egg+veg+rice+dal",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Hilsha Fish + Rice + Dal",
            "L. Hilsha Fish + Rice + Dal (staff)",
            "L. Veg+dal+rice",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice (staff)",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Kima Puri",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Muglai",
            "Lexus Biscuit",
            "Dr. Water (1.0 Ml)",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Kima Puri",
            "Vegetable Roll",
            "Vegetable Singara",
            "L. Veg+dal+rice (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken Polau(staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "Chicken Samucha",
            "Kima Parata",
            "Kima Parata",
            "L. Egg+rice+dal+veg",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Muglai",
            "Pacura",
            "Soup",
            "L. Khasi+rice+dal+(staff)",
            "Tea",
            "Chicken Samucha",
            "I. Vanilla",
            "I. Corneli-classic",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Kima Parata",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Fish/egg+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Vegetable Singara",
            "Egg Puding",
            "Vegetable Singara",
            "Vegetable Singara",
            "Sauce Hot Tomato",
            "Vegetable Singara",
            "Muglai",
            "Kima Puri",
            "Kima Puri",
            "Kima Puri",
            "Dr. Water (0.5) Letter",
            "Dr. Water(1000ml)",
            "Muglai",
            "Kima Puri",
            "Chicken Sandews",
            "Club Sandwich",
            "Egg Puding",
            "Vegetable Singara",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Vegetable Singara",
            "Egg Puding",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Dal",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Egg Puding",
            "Kima Parata",
            "Vegetable Roll",
            "Chicken Samucha",
            "France Fry",
            "L. Dal",
            "Muglai",
            "Sauce Hot Tomato",
            "Vegetable Samucha",
            "Vegetable Samucha",
            "L. Chicken Polau(staff)",
            "Vegetable Singara",
            "Dr. Sprite Botol(200ml)",
            "Dr. Cocacola 200ml",
            "Kima Puri",
            "Beef Burger",
            "Dr. Fanta Botol(200ml)",
            "Dr. Cocacola 200ml",
            "Dr. Fanta Botol(200ml)",
            "Dr. Cocacola 200ml",
            "Vegetable Singara",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "Egg Puding",
            "Tea",
            "Sauce Hot Tomato",
            "Muglai",
            "Kima Puri",
            "Kima Puri",
            "Alachi Biscuit",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Roll",
            "Vegetable Singara",
            "Vegetable Singara",
            "L. Fish/egg+veg+rice+dal (staff)",
            "L. Khasi+rice+dal+(staff)",
            "Egg Puding",
            "L. Egg+rice+dal+veg",
            "L. Veg+dal+rice (staff)",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "Lexus Biscuit",
            "Lexus Biscuit",
            "Kima Puri",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Coffee",
            "L. Fish/egg+veg+rice+dal",
            "L. Khasi+rice+dal",
            "Kima Puri",
            "France Fry",
            "Kima Puri",
            "Vegetable Singara",
            "Vegetable Singara",
            "Kima Puri",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Singara",
            "Kima Puri",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Egg+rice+dal+veg(staff)",
            "L. Khasi+rice+dal+(staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Egg Puding",
            "Dr. Sprite Botol(200ml)",
            "Egg Puding",
            "L. Chicken Polau(staff)",
            "L. Chicken Polau",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Chicken Pizza",
            "Chicken Pizza",
            "Chicken Sandews",
            "Club Sandwich",
            "Beef Burger",
            "Dr. Mirinda 250ml",
            "Dr. Water 1.5 Ltr",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Vegetable Singara",
            "L. Veg+dal+rice (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "Kima Puri",
            "Muglai",
            "I. Chocbar",
            "I. Chocbar",
            "I. Corneli-classic",
            "I. Malay",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Egg+rice+dal+veg(staff)",
            "L. Chicken Polau(staff)",
            "L. Veg+dal+rice (staff)",
            "Vegetable Singara",
            "Vegetable Roll",
            "Kima Parata",
            "France Fry",
            "Beef Burger",
            "Chicken Sandews",
            "Club Sandwich",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Dr. Water (1.0 Ml)",
            "Egg Puding",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish+veg+rice+dal",
            "I. Chocbar",
            "Muglai",
            "Kima Puri",
            "I. Vanilla",
            "I. Shell And- Core",
            "I. Loly",
            "Egg Puding",
            "Vegetable Singara",
            "France Fry",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Vegetable Singara",
            "Chicken Roll",
            "Dr. Pepsi 250ml",
            "Dr. Pepsi 500ml",
            "Dr. Pepsi 500ml Diet",
            "Dr. Mountain Dew 250ml",
            "Vegetable Singara",
            "Kima Puri",
            "Muglai",
            "L. Chicken Polau(staff)",
            "L. Fish+veg+rice+dal (staff)",
            "Egg Puding",
            "Vegetable Singara",
            "Vegetable Roll",
            "L. Veg+dal+rice (staff)",
            "Club Sandwich",
            "Chicken Sandews",
            "Chicken Roll",
            "Chicken Pizza",
            "Chicken Friued Burgar",
            "Beef Burger",
            "Kima Puri",
            "I. Macho",
            "I. Malay",
            "Dr. Sprite (600ml)",
            "France Fry",
            "I. Corneli Belgium Choclate",
            "I. Blackforest Belgium",
            "Dr. 7up 500ml",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Alachi Biscuit",
            "Ekko Biscuits",
            "Ekko Biscuits",
            "L. Fish+veg+rice+dal (staff)",
            "Dr. Sprite Botol(200ml)",
            "Dr. Cocacola Botol(200ml)",
            "Dr. Fanta Botol(200ml)",
            "Kima Puri",
            "Kima Puri",
            "Muglai",
            "I. Chocbar",
            "I. Blackforest Belgium",
            "I. Shell And- Core",
            "I. Loly",
            "I. Malay",
            "I. Mega",
            "I. Macho",
            "I. Vanilla",
            "I. Corneli-classic",
            "I. Corneli Belgium Choclate",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Vegetable Singara",
            "Vegetable Singara",
            "I. Malay",
            "I. Shell And- Core",
            "I. Loly Orange",
            "I. Loly Lemon",
            "I. Vanilla",
            "I. Corneli-classic",
            "I. Corneli Belgium Choclate",
            "L. Fish+veg+rice+dal (staff)",
            "L. Khasi+rice+dal+(staff)",
            "Chicken Pizza",
            "L. Fish+veg+rice+dal (staff)",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "Vegetable Singara",
            "L. Chicken Polau(staff)",
            "L. Egg+rice+dal+veg(staff)",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Singara",
            "Chicken Cutlet",
            "Egg Puding",
            "Kima Parata",
            "Kima Puri",
            "L. Khasi+rice+dal+(staff)",
            "L. Veg+dal+rice (staff)",
            "Egg Puding",
            "L. Beef/ Rice+ Dal+vegetable",
            "Kima Puri",
            "Muglai",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Roll",
            "L. Khasi+rice+dal+(staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "Kima Parata",
            "Kima Puri",
            "L. Veg+dal+rice (staff)",
            "Vegetable Singara",
            "Dr. Mirinda 500ml",
            "Kima Parata",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Vegetable Singara",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Roll",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Sandews",
            "Club Sandwich",
            "L. Veg+dal+rice (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Vegetable Roll",
            "Vegetable Singara",
            "L. Khasi+rice+dal+(staff)",
            "L. Egg+rice+dal+veg(staff)",
            "Kima Parata",
            "Egg Puding",
            "L. Chicken Polau",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish+veg+rice+dal",
            "L. Khasi",
            "L. Khasi+rice+dal",
            "L. Chicken Polau(staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Muglai",
            "Kima Puri",
            "Kima Puri",
            "Vegetable Singara",
            "Vegetable Singara",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Egg Puding",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "L. Beef/ Rice+ Dal+vegetable",
            "Kima Puri",
            "Kima Puri",
            "Vegetable Singara",
            "Kake",
            "L. Fish+veg+rice+dal (staff)",
            "L. Khasi+rice+dal+(staff)",
            "Kima Puri",
            "Kake",
            "Muglai",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "France Fry",
            "Kima Parata",
            "Kima Puri",
            "Vegetable Roll",
            "Vegetable Singara",
            "Vegetable Samucha",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Beef/ Rice+dal+vegetable(staff)",
            "L. Chicken Polau(staff)",
            "L. Khasi+rice+dal+(staff)",
            "D. Fanta Can(250ml)",
            "Egg Puding",
            "Vegetable Singara",
            "Vegetable Samucha",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish+veg+rice+dal",
            "Muglai",
            "Kima Puri",
            "Kima Puri",
            "Kima Puri",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Egg Puding",
            "France Fry",
            "Kima Parata",
            "Kima Puri",
            "L. Thahari (staff)",
            "L. Thahari (staff)",
            "L. Thahari",
            "L. Thahari (staff)",
            "L. Thahari (staff)",
            "Vegetable Roll",
            "Vegetable Singara",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Ruti",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Vegetable Roll",
            "Vegetable Singara",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "I. Chocbar",
            "I. Chocbar",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "Vegetable Singara",
            "Vegetable Roll",
            "Egg Puding",
            "Egg Puding",
            "Kima Puri",
            "Muglai",
            "Egg",
            "Ruti",
            "Ruti",
            "Dr. Cocacola Botol(200ml)",
            "Dr. Fanta Botol(200ml)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "Kima Puri",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Veg+dal+rice (staff)",
            "Egg",
            "Ruti",
            "Vegetable Roll",
            "Vegetable Singara",
            "Muglai",
            "L. Vaji",
            "Egg Puding",
            "Chicken Sandews",
            "Club Sandwich",
            "Kima Parata",
            "France Fry",
            "I. Chocbar",
            "I. Blackforest Belgium",
            "I. Shell And- Core",
            "I. Malay",
            "I. Mega",
            "I. Macho",
            "I. Vanilla",
            "I. Corneli Belgium Choclate",
            "I. Corneli-classic",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Chicken Sandews",
            "Club Sandwich",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken Polau(staff)",
            "L. Chicken Polau",
            "L. Egg+rice+dal+veg",
            "L. Egg+rice+dal+veg(staff)",
            "L. Veg+dal+rice",
            "L. Veg+dal+rice (staff)",
            "Egg Puding",
            "Vegetable Singara",
            "Club Sandwich",
            "Kima Parata",
            "Vegetable Singara",
            "Kima Puri",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "Egg Puding",
            "Vegetable Singara",
            "Chicken Sandews",
            "Club Sandwich",
            "Club Sandwich",
            "Vegetable Roll",
            "Vegetable Roll",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Kima Parata",
            "Sauce Hot Tomato",
            "Sauce Hot Tomato",
            "Vegetable Singara",
            "Club Sandwich",
            "Chicken Sandews",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Egg Puding",
            "L. Fish+veg+rice+dal (staff)",
            "Chicken Sandews",
            "Club Sandwich",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Chicken Sandews",
            "France Fry",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Veg+dal+rice (staff)",
            "L. Egg+rice+dal+veg",
            "Vegetable Roll",
            "Vegetable Singara",
            "L. Veg+dal+rice (staff)",
            "L. Veg+dal+rice",
            "Khichuri",
            "Khichuri",
            "Kima Parata",
            "Egg",
            "Egg",
            "Chicken Sandews",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "Beef Burger",
            "Chicken Friued Burgar",
            "Chicken Pizza",
            "Chicken Roll",
            "Chicken Sandews",
            "Club Sandwich",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Khasi+rice+dal+(staff)",
            "L. Khasi+rice+dal",
            "L. Veg+dal+rice (staff)",
            "Ruti",
            "Vegetable Roll",
            "Vegetable Singara",
            "Vegetable Singara",
            "France Fry",
            "Kima Parata",
            "L. Chicken/fish/meat+veg+rice+dal (staff)",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Chicken/fish/meat+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "L. Fish+veg+rice+dal (staff)",
            "L. Fish+veg+rice+dal",
            "I. Blackforest Belgium",
            "I. Chocbar",
            "F.f Chinese Samucha",
            "F.f Club Sandwich",
            "F.f Koliga Singara",
            "F.f.  France Fry",
            "F.f. Chicken Chili",
            "F.f. Chicken Fried  Burgar",
            "F.f. Chicken Fry",
            "F.f. Chicken Kima Burger",
            "F.f. Chicken Noodles",
            "F.f. Chicken Samucha",
            "F.f. Chicken Sandwich",
            "F.f. Chicken Tost",
            "F.f. Chiken Suslet",
            "F.f. Kima Parata",
            "F.f. Pitha Samucha",
            "F.f. Swiss Roll",
            "F.f. Vegetable Singara",
            "Jao/rice",
            "Juice. Anar",
            "Juice. Apple",
            "Juice. Malta",
            "Juice. Mango",
            "Juice. Pepe",
            "L. Alu Borta",
            "L. Ayir + Rice + Dal + Veg",
            "L. Banana Borta",
            "L. Beef",
            "L. Beef Khichuri",
            "L. Beef Tehari",
            "L. Beef Tehari(staff)",
            "L. Beef/ Rice+dal+veg.",
            "L. Beef/ Rice+dal+veg.(staff)",
            "L. Begun Borta",
            "L. Bowal",
            "L. Boyal Mas+rice+dal+veg.",
            "L. Chicken",
            "L. Chicken Birani",
            "L. Chicken Birani(staff)",
            "L. Chicken Polao",
            "L. Chicken Polau(staff)",
            "L. Chicken+veg+rice+dal",
            "L. Chicken+veg+rice+dal (staff)",
            "L. Chinese Veg.",
            "L. Chingri",
            "L. Chingri Borta",
            "L. Chingri+rice+veg+dal",
            "L. Chingri+veg.+rice+dal(staff)",
            "L. Desi Chicken",
            "L. Desi Chicken+rice+baji+dal(staff)",
            "L. Desi Chikhen+ Rice + Dal+veg.",
            "L. Dim Borta",
            "L. Dim Buna+rice+dal+veg.",
            "L. Egg Fried Rice",
            "L. Egg Vona",
            "L. Egg+rice+dal+veg",
            "L. Egg+rice+dal+veg(staff)",
            "L. Elish Mas",
            "L. Elish+rice+veg.+dal",
            "L. Fish(koi)+rice+ Dal+veg(staff)",
            "L. Fish(koi)+rice+ Dal+veg.",
            "L. Fish(koi/rui)",
            "L. Fish(rui)+rice+veg+dal(staff)",
            "L. Fish(rui)+veg+rice+dal",
            "L. Kabab",
            "L. Khasi+rice+veg+dal",
            "L. Khasi+rice+veg+dal(staff)",
            "L. Komor Borta",
            "L. Maton",
            "L. Matton Polao",
            "L. Rice+veg+dal",
            "L. Rice+veg+dal (staff)",
            "L. Shole",
            "L. Sim Borta",
            "L. Sing Mas+rice+dal+veg.",
            "L. Staff Pakage",
            "L. Taki Mas Borta",
            "L. Telapia Mas+rice+dal+veg",
            "Mutton Resala+pulaoj+egg Kurma",
            "Rice (1/2 Plate)",
            "Rice(full)",
            "Ruti",
            "Soup",
            "Tea",
            "Tomato Sos",
            "Veg",
            "Veg. Soup",
            "Vegetable",
            "Vegetable Khichuri"});
            this.comboBox1.Location = new System.Drawing.Point(206, 40);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(121, 21);
            this.comboBox1.TabIndex = 0;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.dataGridView1);
            this.panel2.Location = new System.Drawing.Point(40, 148);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(728, 252);
            this.panel2.TabIndex = 1;
            // 
            // dataGridView1
            // 
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(34, 50);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.Size = new System.Drawing.Size(240, 150);
            this.dataGridView1.TabIndex = 0;
            // 
            // Stock_report
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(909, 429);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Name = "Stock_report";
            this.Text = "Stock_report";
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.DataGridView dataGridView1;
    }
}